[package]
name = "utils"
version = "0.1.0"
authors = ["fly"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0"
myutil = { git = "https://gitee.com/kt10/myutil", branch = "master" }
rand = "0.7"

